export const UPDATE_RISKS = "UPDATE_RISKS";

export const UPDATE_FAMILY_PROFILE = "UPDATE_FAMILY_PROFILE";

export const UPDATE_SPLASH_INFO = "UPDATE_SPLASH_INFO";

export const UPDATE_BASIC_PROFILE = "UPDATE_BASIC_PROFILE";

export const UPDATE_PHARMACIES = "UPDATE_PHARMACIES";

export const UPDATE_SUMMARY_DETAIL = "UPDATE_SUMMARY_DETAIL";

export const UPDATE_SCHEDULED_TIME = "UPDATE_SCHEDULED_TIME";

export const BOOK_APPOINTMENT = "BOOK_APPOINTMENT";

export const UPDATE_ADMIN_PROFILES = "UPDATE_ADMIN_PROFILES";

export const UPDATE_ADMIN_INPUT = "UPDATE_ADMIN_INPUT";

export const ADMIN_VALIDATION_FAILURE = "ADMIN_VALIDATION_FAILURE";

export const ADMIN_VALIDATION_RESET = "ADMIN_VALIDATION_RESET";

export const UPDATE_SUBMITTED = "UPDATE_SUBMITTED";

export const UPDATE_ADMIN = "UPDATE_ADMIN";

export const UPDATE_PROFILE_DOCTORS = "UPDATE_PROFILE_DOCTORS";

export const UPDATE_PCP_SCHEDULED_TIME = "UPDATE_PCP_SCHEDULED_TIME";

export const BOOK_PCP_APPOINTMENT = "BOOK_PCP_APPOINTMENT";

export const UPDATE_SICK_MARKER = "UPDATE_SICK_MARKER";

export const UPDATE_MAP_REFERENCE = "UPDATE_MAP_REFERENCE";

export const UPDATE_SLIDER_REFERENCE = "UPDATE_SLIDER_REFERENCE";

export const UPDATE_FLU_MARKER = "UPDATE_FLU_MARKER";

export const UPDATE_CAMPAIGN_INFO = "UPDATE_CAMPAIGN_INFO";

export const SEND_SMS_FAILED = "SEND_SMS_FAILED";

export const SENT_SMS_PROGRESS = "SENT_SMS_PROGRESS";

export const SENT_SMS_FINISHED = "SENT_SMS_FINISHED";

export const LOGOUT = "LOGOUT";

export const UPDATE_CAROUSEL_LOCATIONS = "UPDATE_CAROUSEL_LOCATIONS";

export const UPDATE_CAROUSEL_DOC_LOCATIONS = "UPDATE_CAROUSEL_DOC_LOCATIONS";

export const UPDATE_LEARN_INFO = "UPDATE_LEARN_INFO";
